name: Deploy, Build and Run

jobs:
  deploy:
    name: Deploy to EC2
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the files
        uses: actions/checkout@v2

      - name: Deploy to Server 1
        uses: easingthemes/ssh-deploy@main
        env:
          SSH_PRIVATE_KEY: ${{secrets.EC2_SSH_KEY}}
          REMOTE_HOST: "${{secrets.HOST_DNS}}"
          REMOTE_USER: ${{secrets.USERNAME}}
          TARGET: ${{secrets.TARGET_DIR}}

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Building on remote instance
        uses: appleboy/ssh-action@master
        with:
          host: ${{secrets.HOST_DNS}}
          username: ${{secrets.USERNAME}}
          key: ${{secrets.EC2_SSH_KEY}}
          script: |
            cd ~/CC-Project/
            pip3 install -r requirements.txt
            python3 src/run.py --run

on:
  push:
    branches: [main]